version: '2'

networks:
  local:
    driver: 'bridge'

services:
  orchestrator:
    build: .
    networks:
      local:
        aliases:
          - orchestrator.local
    environment:
      ETCD_HOST: 'etcd.local'
      AMQP_HOST: 'rabbitmq.local'
      MONGODB_SERVERS: 'mongo.local:27017'
      DISCOVER_MONGO: 'false'
      DISCOVER_RABBITMQ: 'false'

    ports:
      - 9400

    depends_on:
      - etcd
      - rabbitmq
      - mongo
    restart: always
    volumes:
      - ".:/opt/cluster-orchestrator"

  rabbitmq:
    image: 'rabbitmq:3.6'
    networks:
      local:
        aliases:
          - rabbitmq.local

  mongo:
    image: 'mongo:2.6'
    networks:
      local:
        aliases:
          - mongo.local

  etcd:
    image: 'quay.io/coreos/etcd'
    command: [
      '-name', 'etcd0',
      '-advertise-client-urls','http://etcd.local:2379,http://etcd.local:4001',
      '-listen-client-urls', 'http://0.0.0.0:2379,http://0.0.0.0:4001',
      '-initial-advertise-peer-urls', 'http://etcd.local:2380',
      '-listen-peer-urls', 'http://0.0.0.0:2380',
      '-initial-cluster-token', 'etcd-cluster-1',
      '-initial-cluster', 'etcd0=http://etcd.local:2380',
      '-initial-cluster-state', 'new',
    ]

    networks:
      local:
        aliases:
          - etcd.local
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs